//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico
{
	/// <summary>
	/// DomainModel JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel
	/// Description for
	/// UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.JMGPVRCMAMBModeladoYLenguajeGrafico
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.DisplayName", typeof(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel), "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.Description", typeof(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel), "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("0d73deb0-9472-4c75-be61-8179a1f2c9df")]
	public partial class JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x0d73deb0, 0x9472, 0x4c75, 0xbe, 0x61, 0x81, 0x79, 0xa1, 0xf2, 0xc9, 0xdf);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(ModeloDERAWebBD),
				typeof(Entidad),
				typeof(Atributo),
				typeof(Relacion),
				typeof(Objeto),
				typeof(EstiloGrafico),
				typeof(EGPortalWeb),
				typeof(EGPaginaWeb),
				typeof(EGCampoFormulario),
				typeof(AtributoCP),
				typeof(AtributoSimple),
				typeof(ModeloDERAWebBDHasModeloEntidad),
				typeof(ModeloDERAWebBDHasModeloRelacion),
				typeof(RelacionReferencesRelacionNEntidad),
				typeof(ModeloDERAWebBDHasModeloEG),
				typeof(ObjetoReferencesObjetoAtributoSimple),
				typeof(ModeloDERAWebBDHasModeloAtributoSimple),
				typeof(ModeloDERAWebBDHasModeloAtributoCP),
				typeof(EntidadReferencesEntidadCP),
				typeof(ModeloDERAWebBDHasModeloEGPaginaWeb),
				typeof(EntidadReferencesEntidadEGPaginaWeb),
				typeof(ModeloDERAWebBDHasEGCampoFormulario),
				typeof(AtributoReferencesAtributoEGCampoFormulario),
				typeof(RelacionReferencesRelacionDerEntidad),
				typeof(RelacionReferencesRelacionIzqEntidad),
				typeof(JMGPVRCMAMBModeladoYLenguajeGraficoDiagram),
				typeof(MetaforaRNE),
				typeof(MetaforaConexion),
				typeof(MetaforaConexionCP),
				typeof(MetaforaEGPaginaEntidad),
				typeof(MetaforaEGCamposAtributos),
				typeof(MetaforaRDE),
				typeof(MetaforaRIE),
				typeof(MetaforaEntidad),
				typeof(MetaforaAtributo),
				typeof(MetaforaRelacion),
				typeof(MetaforaAtributoClave),
				typeof(MetaforaEGPortal),
				typeof(MetaforaEGPagnaWeb),
				typeof(MetaforaEGCampoFormulario),
				typeof(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.FixUpDiagram),
				typeof(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.DecoratorPropertyChanged),
				typeof(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(ModeloDERAWebBD), "Titulo", ModeloDERAWebBD.TituloDomainPropertyId, typeof(ModeloDERAWebBD.TituloPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "Nombre", Atributo.NombreDomainPropertyId, typeof(Atributo.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "TipoDatos", Atributo.TipoDatosDomainPropertyId, typeof(Atributo.TipoDatosPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "Longitud", Atributo.LongitudDomainPropertyId, typeof(Atributo.LongitudPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "NombreTipo", Atributo.NombreTipoDomainPropertyId, typeof(Atributo.NombreTipoPropertyHandler)),
				new DomainMemberInfo(typeof(Relacion), "cardinalidadRelacion", Relacion.cardinalidadRelacionDomainPropertyId, typeof(Relacion.cardinalidadRelacionPropertyHandler)),
				new DomainMemberInfo(typeof(Objeto), "Nombre", Objeto.NombreDomainPropertyId, typeof(Objeto.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGrafico), "Color", EstiloGrafico.ColorDomainPropertyId, typeof(EstiloGrafico.ColorPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGrafico), "Tamaño", EstiloGrafico.TamañoDomainPropertyId, typeof(EstiloGrafico.TamañoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGrafico), "Alineacion", EstiloGrafico.AlineacionDomainPropertyId, typeof(EstiloGrafico.AlineacionPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGrafico), "TipoLetra", EstiloGrafico.TipoLetraDomainPropertyId, typeof(EstiloGrafico.TipoLetraPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGrafico), "Nombre", EstiloGrafico.NombreDomainPropertyId, typeof(EstiloGrafico.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(EGPortalWeb), "Fondo", EGPortalWeb.FondoDomainPropertyId, typeof(EGPortalWeb.FondoPropertyHandler)),
				new DomainMemberInfo(typeof(EGCampoFormulario), "FormatoVisualizacion", EGCampoFormulario.FormatoVisualizacionDomainPropertyId, typeof(EGCampoFormulario.FormatoVisualizacionPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoSimple), "esUnico", AtributoSimple.esUnicoDomainPropertyId, typeof(AtributoSimple.esUnicoPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoSimple), "puedeSerNulo", AtributoSimple.puedeSerNuloDomainPropertyId, typeof(AtributoSimple.puedeSerNuloPropertyHandler)),
				new DomainMemberInfo(typeof(RelacionReferencesRelacionNEntidad), "cardilidad", RelacionReferencesRelacionNEntidad.cardilidadDomainPropertyId, typeof(RelacionReferencesRelacionNEntidad.cardilidadPropertyHandler)),
				new DomainMemberInfo(typeof(RelacionReferencesRelacionDerEntidad), "cardinalidadDer", RelacionReferencesRelacionDerEntidad.cardinalidadDerDomainPropertyId, typeof(RelacionReferencesRelacionDerEntidad.cardinalidadDerPropertyHandler)),
				new DomainMemberInfo(typeof(RelacionReferencesRelacionIzqEntidad), "cardinalidadIzq", RelacionReferencesRelacionIzqEntidad.cardinalidadIzqDomainPropertyId, typeof(RelacionReferencesRelacionIzqEntidad.cardinalidadIzqPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(ModeloDERAWebBDHasModeloEntidad), "ModeloDERAWebBD", ModeloDERAWebBDHasModeloEntidad.ModeloDERAWebBDDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModeloDERAWebBDHasModeloEntidad), "Entidad", ModeloDERAWebBDHasModeloEntidad.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModeloDERAWebBDHasModeloRelacion), "ModeloDERAWebBD", ModeloDERAWebBDHasModeloRelacion.ModeloDERAWebBDDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModeloDERAWebBDHasModeloRelacion), "Relacion", ModeloDERAWebBDHasModeloRelacion.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesRelacionNEntidad), "Relacion", RelacionReferencesRelacionNEntidad.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesRelacionNEntidad), "Entidad", RelacionReferencesRelacionNEntidad.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModeloDERAWebBDHasModeloEG), "ModeloDERAWebBD", ModeloDERAWebBDHasModeloEG.ModeloDERAWebBDDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModeloDERAWebBDHasModeloEG), "EGPortalWeb", ModeloDERAWebBDHasModeloEG.EGPortalWebDomainRoleId),
				new DomainRolePlayerInfo(typeof(ObjetoReferencesObjetoAtributoSimple), "Objeto", ObjetoReferencesObjetoAtributoSimple.ObjetoDomainRoleId),
				new DomainRolePlayerInfo(typeof(ObjetoReferencesObjetoAtributoSimple), "AtributoSimple", ObjetoReferencesObjetoAtributoSimple.AtributoSimpleDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModeloDERAWebBDHasModeloAtributoSimple), "ModeloDERAWebBD", ModeloDERAWebBDHasModeloAtributoSimple.ModeloDERAWebBDDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModeloDERAWebBDHasModeloAtributoSimple), "AtributoSimple", ModeloDERAWebBDHasModeloAtributoSimple.AtributoSimpleDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModeloDERAWebBDHasModeloAtributoCP), "ModeloDERAWebBD", ModeloDERAWebBDHasModeloAtributoCP.ModeloDERAWebBDDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModeloDERAWebBDHasModeloAtributoCP), "AtributoCP", ModeloDERAWebBDHasModeloAtributoCP.AtributoCPDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesEntidadCP), "Entidad", EntidadReferencesEntidadCP.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesEntidadCP), "AtributoCP", EntidadReferencesEntidadCP.AtributoCPDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModeloDERAWebBDHasModeloEGPaginaWeb), "ModeloDERAWebBD", ModeloDERAWebBDHasModeloEGPaginaWeb.ModeloDERAWebBDDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModeloDERAWebBDHasModeloEGPaginaWeb), "EGPaginaWeb", ModeloDERAWebBDHasModeloEGPaginaWeb.EGPaginaWebDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesEntidadEGPaginaWeb), "Entidad", EntidadReferencesEntidadEGPaginaWeb.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesEntidadEGPaginaWeb), "EGPaginaWeb", EntidadReferencesEntidadEGPaginaWeb.EGPaginaWebDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModeloDERAWebBDHasEGCampoFormulario), "ModeloDERAWebBD", ModeloDERAWebBDHasEGCampoFormulario.ModeloDERAWebBDDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModeloDERAWebBDHasEGCampoFormulario), "EGCampoFormulario", ModeloDERAWebBDHasEGCampoFormulario.EGCampoFormularioDomainRoleId),
				new DomainRolePlayerInfo(typeof(AtributoReferencesAtributoEGCampoFormulario), "Atributo", AtributoReferencesAtributoEGCampoFormulario.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(AtributoReferencesAtributoEGCampoFormulario), "EGCampoFormulario", AtributoReferencesAtributoEGCampoFormulario.EGCampoFormularioDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesRelacionDerEntidad), "Relacion", RelacionReferencesRelacionDerEntidad.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesRelacionDerEntidad), "Entidad", RelacionReferencesRelacionDerEntidad.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesRelacionIzqEntidad), "Relacion", RelacionReferencesRelacionIzqEntidad.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesRelacionIzqEntidad), "Entidad", RelacionReferencesRelacionIzqEntidad.EntidadDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(26);
				createElementMap.Add(typeof(ModeloDERAWebBD), 0);
				createElementMap.Add(typeof(Entidad), 1);
				createElementMap.Add(typeof(Relacion), 2);
				createElementMap.Add(typeof(EGPortalWeb), 3);
				createElementMap.Add(typeof(EGPaginaWeb), 4);
				createElementMap.Add(typeof(EGCampoFormulario), 5);
				createElementMap.Add(typeof(AtributoCP), 6);
				createElementMap.Add(typeof(AtributoSimple), 7);
				createElementMap.Add(typeof(JMGPVRCMAMBModeladoYLenguajeGraficoDiagram), 8);
				createElementMap.Add(typeof(MetaforaRNE), 9);
				createElementMap.Add(typeof(MetaforaConexion), 10);
				createElementMap.Add(typeof(MetaforaConexionCP), 11);
				createElementMap.Add(typeof(MetaforaEGPaginaEntidad), 12);
				createElementMap.Add(typeof(MetaforaEGCamposAtributos), 13);
				createElementMap.Add(typeof(MetaforaRDE), 14);
				createElementMap.Add(typeof(MetaforaRIE), 15);
				createElementMap.Add(typeof(MetaforaEntidad), 16);
				createElementMap.Add(typeof(MetaforaAtributo), 17);
				createElementMap.Add(typeof(MetaforaRelacion), 18);
				createElementMap.Add(typeof(MetaforaAtributoClave), 19);
				createElementMap.Add(typeof(MetaforaEGPortal), 20);
				createElementMap.Add(typeof(MetaforaEGPagnaWeb), 21);
				createElementMap.Add(typeof(MetaforaEGCampoFormulario), 22);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new ModeloDERAWebBD(partition, propertyAssignments);
				case 1: return new Entidad(partition, propertyAssignments);
				case 2: return new Relacion(partition, propertyAssignments);
				case 3: return new EGPortalWeb(partition, propertyAssignments);
				case 4: return new EGPaginaWeb(partition, propertyAssignments);
				case 5: return new EGCampoFormulario(partition, propertyAssignments);
				case 6: return new AtributoCP(partition, propertyAssignments);
				case 7: return new AtributoSimple(partition, propertyAssignments);
				case 8: return new JMGPVRCMAMBModeladoYLenguajeGraficoDiagram(partition, propertyAssignments);
				case 9: return new MetaforaRNE(partition, propertyAssignments);
				case 10: return new MetaforaConexion(partition, propertyAssignments);
				case 11: return new MetaforaConexionCP(partition, propertyAssignments);
				case 12: return new MetaforaEGPaginaEntidad(partition, propertyAssignments);
				case 13: return new MetaforaEGCamposAtributos(partition, propertyAssignments);
				case 14: return new MetaforaRDE(partition, propertyAssignments);
				case 15: return new MetaforaRIE(partition, propertyAssignments);
				case 16: return new MetaforaEntidad(partition, propertyAssignments);
				case 17: return new MetaforaAtributo(partition, propertyAssignments);
				case 18: return new MetaforaRelacion(partition, propertyAssignments);
				case 19: return new MetaforaAtributoClave(partition, propertyAssignments);
				case 20: return new MetaforaEGPortal(partition, propertyAssignments);
				case 21: return new MetaforaEGPagnaWeb(partition, propertyAssignments);
				case 22: return new MetaforaEGCampoFormulario(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(14);
				createElementLinkMap.Add(typeof(ModeloDERAWebBDHasModeloEntidad), 0);
				createElementLinkMap.Add(typeof(ModeloDERAWebBDHasModeloRelacion), 1);
				createElementLinkMap.Add(typeof(RelacionReferencesRelacionNEntidad), 2);
				createElementLinkMap.Add(typeof(ModeloDERAWebBDHasModeloEG), 3);
				createElementLinkMap.Add(typeof(ObjetoReferencesObjetoAtributoSimple), 4);
				createElementLinkMap.Add(typeof(ModeloDERAWebBDHasModeloAtributoSimple), 5);
				createElementLinkMap.Add(typeof(ModeloDERAWebBDHasModeloAtributoCP), 6);
				createElementLinkMap.Add(typeof(EntidadReferencesEntidadCP), 7);
				createElementLinkMap.Add(typeof(ModeloDERAWebBDHasModeloEGPaginaWeb), 8);
				createElementLinkMap.Add(typeof(EntidadReferencesEntidadEGPaginaWeb), 9);
				createElementLinkMap.Add(typeof(ModeloDERAWebBDHasEGCampoFormulario), 10);
				createElementLinkMap.Add(typeof(AtributoReferencesAtributoEGCampoFormulario), 11);
				createElementLinkMap.Add(typeof(RelacionReferencesRelacionDerEntidad), 12);
				createElementLinkMap.Add(typeof(RelacionReferencesRelacionIzqEntidad), 13);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new ModeloDERAWebBDHasModeloEntidad(partition, roleAssignments, propertyAssignments);
				case 1: return new ModeloDERAWebBDHasModeloRelacion(partition, roleAssignments, propertyAssignments);
				case 2: return new RelacionReferencesRelacionNEntidad(partition, roleAssignments, propertyAssignments);
				case 3: return new ModeloDERAWebBDHasModeloEG(partition, roleAssignments, propertyAssignments);
				case 4: return new ObjetoReferencesObjetoAtributoSimple(partition, roleAssignments, propertyAssignments);
				case 5: return new ModeloDERAWebBDHasModeloAtributoSimple(partition, roleAssignments, propertyAssignments);
				case 6: return new ModeloDERAWebBDHasModeloAtributoCP(partition, roleAssignments, propertyAssignments);
				case 7: return new EntidadReferencesEntidadCP(partition, roleAssignments, propertyAssignments);
				case 8: return new ModeloDERAWebBDHasModeloEGPaginaWeb(partition, roleAssignments, propertyAssignments);
				case 9: return new EntidadReferencesEntidadEGPaginaWeb(partition, roleAssignments, propertyAssignments);
				case 10: return new ModeloDERAWebBDHasEGCampoFormulario(partition, roleAssignments, propertyAssignments);
				case 11: return new AtributoReferencesAtributoEGCampoFormulario(partition, roleAssignments, propertyAssignments);
				case 12: return new RelacionReferencesRelacionDerEntidad(partition, roleAssignments, propertyAssignments);
				case 13: return new RelacionReferencesRelacionIzqEntidad(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.resourceManager == null)
				{
					JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel).Assembly);
				}
				return JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new JMGPVRCMAMBModeladoYLenguajeGraficoCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.copyClosure = copyFilter;
				}
				return JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new JMGPVRCMAMBModeladoYLenguajeGraficoDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.removeClosure = removeFilter;
				}
				return JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class JMGPVRCMAMBModeladoYLenguajeGraficoDeleteClosure : JMGPVRCMAMBModeladoYLenguajeGraficoDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public JMGPVRCMAMBModeladoYLenguajeGraficoDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class JMGPVRCMAMBModeladoYLenguajeGraficoDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public JMGPVRCMAMBModeladoYLenguajeGraficoDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ModeloDERAWebBDHasModeloEntidad.EntidadDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ModeloDERAWebBDHasModeloRelacion.RelacionDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ModeloDERAWebBDHasModeloEG.EGPortalWebDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ModeloDERAWebBDHasModeloAtributoSimple.AtributoSimpleDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ModeloDERAWebBDHasModeloAtributoCP.AtributoCPDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ModeloDERAWebBDHasModeloEGPaginaWeb.EGPaginaWebDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ModeloDERAWebBDHasEGCampoFormulario.EGCampoFormularioDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class JMGPVRCMAMBModeladoYLenguajeGraficoCopyClosure : JMGPVRCMAMBModeladoYLenguajeGraficoCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public JMGPVRCMAMBModeladoYLenguajeGraficoCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class JMGPVRCMAMBModeladoYLenguajeGraficoCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public JMGPVRCMAMBModeladoYLenguajeGraficoCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico
{
	/// <summary>
	/// DomainEnumeration: TipoCardinalidad
	/// Description for UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.TipoCardinalidad
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoCardinalidad
	{
		/// <summary>
		/// hola
		/// Cardinalidad 1
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.TipoCardinalidad/hola.Description", typeof(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel), "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.GeneratedCode.DomainModelResx")]
		hola = 0,
	}
}

