//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Windows.Forms;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico
{
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	/// <remarks>
	/// Double-derived class to allow easier code customization.
	/// </remarks>
	public partial class JMGPVRCMAMBModeladoYLenguajeGraficoToolboxHelper : JMGPVRCMAMBModeladoYLenguajeGraficoToolboxHelperBase 
	{
		/// <summary>
		/// Constructs a new JMGPVRCMAMBModeladoYLenguajeGraficoToolboxHelper.
		/// </summary>
		public JMGPVRCMAMBModeladoYLenguajeGraficoToolboxHelper(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider) { }
	}
	
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Justification = "The store is disposed on domain shut down")]
	public abstract class JMGPVRCMAMBModeladoYLenguajeGraficoToolboxHelperBase
	{
		/// <summary>
		/// Toolbox item filter string used to identify JMGPVRCMAMBModeladoYLenguajeGrafico toolbox items.  
		/// </summary>
		/// <remarks>
		/// See the MSDN documentation for the ToolboxItemFilterAttribute class for more information on toolbox
		/// item filters.
		/// </remarks>
		public const string ToolboxFilterString = "JMGPVRCMAMBModeladoYLenguajeGrafico.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify RelacionNEntidad connector tool.
		/// </summary>
		public const string RelacionNEntidadFilterString = "RelacionNEntidad.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify RelacionDerEntidad connector tool.
		/// </summary>
		public const string RelacionDerEntidadFilterString = "RelacionDerEntidad.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify RelacionIzqEntidad connector tool.
		/// </summary>
		public const string RelacionIzqEntidadFilterString = "RelacionIzqEntidad.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify ConectarAtributo connector tool.
		/// </summary>
		public const string ConectarAtributoFilterString = "ConectarAtributo.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify EntidadClave connector tool.
		/// </summary>
		public const string EntidadClaveFilterString = "EntidadClave.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify EGPaginaEntidad connector tool.
		/// </summary>
		public const string EGPaginaEntidadFilterString = "EGPaginaEntidad.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify EGCamposFormularioAtributo connector tool.
		/// </summary>
		public const string EGCamposFormularioAtributoFilterString = "EGCamposFormularioAtributo.1.0";

	
		private global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem> toolboxItemCache = new global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem>();
		private DslModeling::Store toolboxStore;
		
		private global::System.IServiceProvider sp;
		
		/// <summary>
		/// Constructs a new JMGPVRCMAMBModeladoYLenguajeGraficoToolboxHelperBase.
		/// </summary>
		protected JMGPVRCMAMBModeladoYLenguajeGraficoToolboxHelperBase(global::System.IServiceProvider serviceProvider)
		{
			if(serviceProvider == null) throw new global::System.ArgumentNullException("serviceProvider");
			
			this.sp = serviceProvider;
		}
		
		/// <summary>
		/// Serivce provider used to access services from the hosting environment.
		/// </summary>
		protected global::System.IServiceProvider ServiceProvider
		{
			get
			{
				return this.sp;
			}
		}

		/// <summary>
		/// Returns the display name of the tab that should be opened by default when the editor is opened.
		/// </summary>
		public static string DefaultToolboxTabName
		{
			get
			{
				return global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.SingletonResourceManager.GetString("ObjetosToolboxTab", global::System.Globalization.CultureInfo.CurrentUICulture);
			}
		}
		
		
		/// <summary>
		/// Returns the toolbox items count in the default tool box tab.
		/// </summary>
		public static int DefaultToolboxTabToolboxItemsCount
		{
			get
			{
				return 4;
			}
		}
		

		/// <summary>
		/// Returns a list of custom toolbox items to be added dynamically
		/// </summary>
		public virtual global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem> toolboxItems = new global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem>();
			return toolboxItems;
		}
		
		/// <summary>
		/// Creates an ElementGroupPrototype for the element tool corresponding to the given domain class id.
		/// Default behavior is to create a prototype containing an instance of the domain class.
		/// Derived classes may override this to add additional information to the prototype.
		/// </summary>
		protected virtual DslModeling::ElementGroupPrototype CreateElementToolPrototype(DslModeling::Store store, global::System.Guid domainClassId)
		{
			DslModeling::ModelElement element = store.ElementFactory.CreateElement(domainClassId);
			DslModeling::ElementGroup elementGroup = new DslModeling::ElementGroup(store.DefaultPartition);
			elementGroup.AddGraph(element, true);
			return elementGroup.CreatePrototype();
		}

		/// <summary>
		/// Returns instance of ModelingToolboxItem based on specified name.
		/// This method must be called from within a Transaction. Failure to do so will result in an exception
		/// </summary>
		/// <param name="itemId">unique name of desired ToolboxItem</param>
		/// <param name="store">Store to perform the operation against</param>
		/// <returns>An instance of ModelingToolboxItem if the itemId can be resolved, null otherwise</returns>
		public virtual DslDesign::ModelingToolboxItem GetToolboxItem(string itemId, DslModeling::Store store)
		{
			DslDesign::ModelingToolboxItem result = null;
			if (string.IsNullOrEmpty(itemId))
			{
				return null;
			}
			if (store == null)
			{
				return null;
			}
			global::System.Resources.ResourceManager resourceManager = global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;
			switch(itemId)
			{
				case "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EntidadToolboxItem":
					// Add Entidad shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EntidadToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EntidadToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EntidadToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ObjetosToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ObjetosToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Entidad", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EntidadToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.Entidad.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.AtributoToolboxItem":
					// Add Atributo shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.AtributoToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AtributoToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AtributoToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ObjetosToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ObjetosToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Atributo", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AtributoToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.AtributoSimple.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.RelacionBinariaToolboxItem":
					// Add RelacionBinaria shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.RelacionBinariaToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("RelacionBinariaToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("RelacionBinariaToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ObjetosToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ObjetosToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"RelacionBinaria", // F1 help keyword for the toolbox item.
						resourceManager.GetString("RelacionBinariaToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.Relacion.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ClavePrimariaToolboxItem":
					// Add ClavePrimaria shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ClavePrimariaToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ClavePrimariaToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ClavePrimariaToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ObjetosToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ObjetosToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ClavePrimaria", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ClavePrimariaToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.AtributoCP.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.RelacionNEntidadToolboxItem":

					// Add RelacionNEntidad connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.RelacionNEntidadToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("RelacionNEntidadToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("RelacionNEntidadToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EnlacesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnlacesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"RelacionNEntidad", // F1 help keyword for the toolbox item.
						resourceManager.GetString("RelacionNEntidadToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(RelacionNEntidadFilterString)
						});
					break;
				case "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.RelacionDerEntidadToolboxItem":

					// Add RelacionDerEntidad connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.RelacionDerEntidadToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("RelacionDerEntidadToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("RelacionDerEntidadToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EnlacesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnlacesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"RelacionDerEntidad", // F1 help keyword for the toolbox item.
						resourceManager.GetString("RelacionDerEntidadToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(RelacionDerEntidadFilterString)
						});
					break;
				case "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.RelacionIzqEntidadToolboxItem":

					// Add RelacionIzqEntidad connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.RelacionIzqEntidadToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("RelacionIzqEntidadToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("RelacionIzqEntidadToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EnlacesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnlacesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"RelacionIzqEntidad", // F1 help keyword for the toolbox item.
						resourceManager.GetString("RelacionIzqEntidadToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(RelacionIzqEntidadFilterString)
						});
					break;
				case "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ConectarAtributoToolboxItem":

					// Add ConectarAtributo connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.ConectarAtributoToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ConectarAtributoToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ConectarAtributoToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EnlacesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnlacesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ConectarAtributo", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ConectarAtributoToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ConectarAtributoFilterString)
						});
					break;
				case "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EntidadClaveToolboxItem":

					// Add EntidadClave connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EntidadClaveToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EntidadClaveToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EntidadClaveToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EnlacesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnlacesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EntidadClave", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EntidadClaveToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(EntidadClaveFilterString)
						});
					break;
				case "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EGPaginaEntidadToolboxItem":

					// Add EGPaginaEntidad connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EGPaginaEntidadToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						6, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EGPaginaEntidadToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EGPaginaEntidadToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EnlacesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnlacesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EGPaginaEntidad", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EGPaginaEntidadToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(EGPaginaEntidadFilterString)
						});
					break;
				case "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EGCamposFormularioAtributoToolboxItem":

					// Add EGCamposFormularioAtributo connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EGCamposFormularioAtributoToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						7, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EGCamposFormularioAtributoToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EGCamposFormularioAtributoToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EnlacesToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EnlacesToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EGCamposFormularioAtributo", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EGCamposFormularioAtributoToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(EGCamposFormularioAtributoFilterString)
						});
					break;
				case "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.PortalWebToolboxItem":
					// Add PortalWeb shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.PortalWebToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("PortalWebToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("PortalWebToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EstilosToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EstilosToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"PortalWeb", // F1 help keyword for the toolbox item.
						resourceManager.GetString("PortalWebToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EGPortalWeb.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.PaginaWebToolboxItem":
					// Add PaginaWeb shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.PaginaWebToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("PaginaWebToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("PaginaWebToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EstilosToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EstilosToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"PaginaWeb", // F1 help keyword for the toolbox item.
						resourceManager.GetString("PaginaWebToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EGPaginaWeb.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.CamposFormularioToolboxItem":
					// Add CamposFormulario shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.CamposFormularioToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("CamposFormularioToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("CamposFormularioToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EstilosToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("EstilosToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"CamposFormulario", // F1 help keyword for the toolbox item.
						resourceManager.GetString("CamposFormularioToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.EGCampoFormulario.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				default:
					break;
			} // end switch
			
			return result;
		}
		

		/// <summary>
		/// The store toe be used for all the toolbox item creation
		/// </summary>
		protected DslModeling::Store ToolboxStore
		{
			get
			{ 
				if (toolboxStore==null)
				{
					toolboxStore = new DslModeling::Store(this.ServiceProvider);
					EventHandler StoreCleanUp = (o, e) =>
					{
						//Since Store implements IDisposable, we need to dispose it when we're finished
						if (this.toolboxStore != null)
						{
							this.toolboxStore.Dispose();
						}
						this.toolboxStore = null;
					};
					//There is no DomainUnload event for the default AppDomain, so we listen for both ProcessExit and DomainUnload
					AppDomain.CurrentDomain.ProcessExit += new EventHandler(StoreCleanUp);
					AppDomain.CurrentDomain.DomainUnload += new EventHandler(StoreCleanUp);
					
					//load the domain model
					toolboxStore.LoadDomainModels(typeof(global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel));
					
				}
				return toolboxStore;
			}
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" returns the the toolbox item using cached dictionary
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve</param>
		private DslDesign::ModelingToolboxItem GetToolboxItem(string itemId)
		{
			DslDesign::ModelingToolboxItem item = null;

			if (!this.toolboxItemCache.TryGetValue(itemId, out item))
			{
				DslModeling::Store store = this.ToolboxStore;
				
				// Open transaction so we can create model elements corresponding to toolbox items.
				using (DslModeling::Transaction t = store.TransactionManager.BeginTransaction("CreateToolboxItems"))
				{
					// Retrieve the specified ToolboxItem from the DSL
					this.toolboxItemCache[itemId] = item = this.GetToolboxItem(itemId, store);
				}
			}

			return item;
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		public virtual object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			DslDesign::ModelingToolboxItem item = null;

			global::System.Resources.ResourceManager resourceManager = global::UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico.JMGPVRCMAMBModeladoYLenguajeGraficoDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;

			System.Windows.Forms.IDataObject tbxDataObj;

			//get the toolbox item
			item = GetToolboxItem(itemId);

			if (item != null)
			{
				ToolboxItemContainer container = new ToolboxItemContainer(item);
				tbxDataObj = container.ToolboxData;

				if (tbxDataObj.GetDataPresent(format.Name))
				{
					return tbxDataObj.GetData(format.Name);
				}
				else 
				{
					string invalidFormatString = resourceManager.GetString("UnsupportedToolboxFormat", resourceCulture);
					throw new InvalidOperationException(string.Format(resourceCulture, invalidFormatString, format.Name));
				}
			}

			string errorFormatString = resourceManager.GetString("UnresolvedToolboxItem", resourceCulture);
			throw new InvalidOperationException(string.Format(resourceCulture, errorFormatString, itemId));
		}		
	}
}
