//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "JMGPVRCMAMB_DSLProyIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"JMGPVRCMAMBModeladoYLenguajeGrafico";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID JMGPVRCMAMBModeladoYLenguajeGraficoDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(JMGPVRCMAMBModeladoYLenguajeGraficoCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID JMGPVRCMAMBModeladoYLenguajeGraficoExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(JMGPVRCMAMBModeladoYLenguajeGraficoCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewJMGPVRCMAMBModeladoYLenguajeGraficoExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(JMGPVRCMAMBModeladoYLenguajeGraficoCommandSetId), 0x0001);
	
		// Package identifier
		public const string JMGPVRCMAMBModeladoYLenguajeGraficoPackageId = "c9ab4052-fec2-4909-8643-7c9338a152f2";
		
		// Editor factory identifier
		public const string JMGPVRCMAMBModeladoYLenguajeGraficoEditorFactoryId = "cf6aa646-026d-4fb8-a209-c5c608e82fec";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string JMGPVRCMAMBModeladoYLenguajeGraficoModelExplorerToolWindowId = "8ee62b6d-8abf-42e9-a4fe-ccafc18e1cbb";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.JMGPVRCMAMBModeladoYLenguajeGrafico
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string JMGPVRCMAMBModeladoYLenguajeGraficoCommandSetId = "238bbd90-54cc-488e-851a-55f4d451170b";
	}
}